import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#FCF9F8',
  },
  sidebar: {
    width: 260,
    flexShrink: 0,
    backgroundColor: '#FFFFFF',
    borderRightWidth: 1,
    borderRightColor: '#E8DEDC',
  },
  businessHeader: {
    minHeight: 98,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  logo: {
    width: 50,
    height: 50,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#A80000',
  },
  logoText: {
    color: '#FFFFFF',
    fontSize: 21,
    fontWeight: '800',
  },
  businessInformation: {
    flex: 1,
    minWidth: 0,
  },
  brandName: {
    color: '#171211',
    fontSize: 18,
    fontWeight: '800',
  },
  businessName: {
    marginTop: 4,
    color: '#634A46',
    fontSize: 12,
  },
  posBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 5,
    backgroundColor: '#F0ECEB',
  },
  posText: {
    color: '#4B302C',
    fontSize: 10,
    fontWeight: '700',
  },
  divider: {
    height: 1,
    backgroundColor: '#E8DEDC',
  },
  navigation: {
    flex: 1,
    paddingHorizontal: 12,
    paddingTop: 14,
    gap: 5,
  },
  navigationItem: {
    minHeight: 45,
    paddingHorizontal: 15,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  navigationItemActive: {
    backgroundColor: '#C90000',
  },
  navigationItemPressed: {
    opacity: 0.8,
  },
  navigationIcon: {
    width: 22,
    color: '#5C211B',
    fontSize: 19,
    textAlign: 'center',
    fontWeight: '700',
  },
  navigationText: {
    flex: 1,
    color: '#4F2924',
    fontSize: 15,
    fontWeight: '600',
  },
  navigationTextActive: {
    color: '#FFFFFF',
  },
  soonBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 5,
    backgroundColor: '#F0ECEB',
  },
  soonText: {
    color: '#6D5753',
    fontSize: 9,
  },
  sidebarFooter: {
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: '#E8DEDC',
    gap: 10,
  },
  helpButton: {
    minHeight: 40,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 13,
  },
  helpIcon: {
    width: 22,
    color: '#53231E',
    fontSize: 17,
    fontWeight: '800',
    textAlign: 'center',
  },
  helpText: {
    color: '#4F2924',
    fontSize: 14,
    fontWeight: '600',
  },
  accountCard: {
    padding: 10,
    borderRadius: 9,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#F5F1F0',
  },
  avatarSmall: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#E5E0DF',
  },
  avatarText: {
    color: '#171211',
    fontSize: 15,
    fontWeight: '800',
  },
  accountInformation: {
    flex: 1,
  },
  accountName: {
    color: '#211716',
    fontSize: 13,
    fontWeight: '700',
  },
  accountRole: {
    marginTop: 2,
    color: '#725E5A',
    fontSize: 11,
  },
  logoutButton: {
    padding: 6,
  },
  logoutText: {
    color: '#5E2822',
    fontSize: 21,
    fontWeight: '700',
  },
  workspace: {
    flex: 1,
    minWidth: 0,
  },
  topbar: {
    height: 76,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#E8DEDC',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 18,
  },
  compactBrand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  compactLogo: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#A80000',
  },
  compactLogoText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  compactBrandText: {
    color: '#181312',
    fontSize: 18,
    fontWeight: '800',
  },
  searchContainer: {
    width: 360,
    height: 40,
    paddingHorizontal: 15,
    borderWidth: 1,
    borderColor: '#DDD3D1',
    borderRadius: 9,
    backgroundColor: '#F7F3F2',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  searchContainerCompact: {
    flex: 1,
    width: undefined,
  },
  searchIcon: {
    color: '#53231E',
    fontSize: 21,
  },
  searchInput: {
    flex: 1,
    height: 38,
    color: '#251817',
    fontSize: 13,
  },
  topbarActions: {
    marginLeft: 'auto',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  iconButton: {
    width: 40,
    height: 40,
    borderWidth: 1,
    borderColor: '#E2D8D6',
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFF',
  },
  actionIcon: {
    color: '#57241F',
    fontSize: 18,
    fontWeight: '700',
  },
  topbarSeparator: {
    width: 1,
    height: 28,
    marginHorizontal: 4,
    backgroundColor: '#E1D7D5',
  },
  profileButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#A80000',
  },
  profileIcon: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '800',
  },
  buttonPressed: {
    opacity: 0.65,
  },
  routeContainer: {
    flex: 1,
    minHeight: 0,
    backgroundColor: '#FCF9F8',
  },
});