import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  scrollView: {
    flex: 1,
    backgroundColor: '#FCF9F8',
  },
  content: {
    width: '100%',
    maxWidth: 1500,
    alignSelf: 'center',
    paddingHorizontal: 28,
    paddingTop: 28,
    paddingBottom: 40,
    gap: 28,
  },
  contentNarrow: {
    paddingHorizontal: 16,
    paddingTop: 20,
    gap: 20,
  },
  pageHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 20,
  },
  pageHeaderNarrow: {
    alignItems: 'flex-start',
    flexDirection: 'column',
  },
  titleArea: {
    gap: 6,
  },
  pageTitle: {
    color: '#181211',
    fontSize: 29,
    lineHeight: 35,
    fontWeight: '800',
  },
  pageSubtitle: {
    color: '#633B35',
    fontSize: 15,
  },
  headerControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  headerControlsNarrow: {
    width: '100%',
  },
  dateCard: {
    minHeight: 44,
    minWidth: 260,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: '#E3D9D7',
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
    boxShadow: '0 1px 2px rgba(40, 18, 15, 0.06)',
  },
  dateIcon: {
    color: '#6E302A',
    fontSize: 17,
    fontWeight: '700',
  },
  dateText: {
    color: '#4F2924',
    fontSize: 13,
    fontWeight: '500',
  },
  notificationButton: {
    width: 44,
    height: 44,
    borderWidth: 1,
    borderColor: '#E3D9D7',
    borderRadius: 9,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    boxShadow: '0 1px 2px rgba(40, 18, 15, 0.06)',
  },
  notificationIcon: {
    color: '#632B25',
    fontSize: 20,
  },
  notificationDot: {
    position: 'absolute',
    top: 9,
    right: 9,
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#A8837E',
  },
  pressed: {
    opacity: 0.7,
  },
  headerDivider: {
    height: 1,
    backgroundColor: '#E5DBD9',
  },
  phaseBanner: {
    minHeight: 78,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: '#E3D9D7',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    boxShadow: '0 2px 4px rgba(40, 18, 15, 0.05)',
  },
  phaseIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F2EEEE',
  },
  phaseIcon: {
    color: '#171211',
    fontSize: 14,
    fontWeight: '800',
  },
  phaseInformation: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  phaseTitle: {
    color: '#1D1514',
    fontSize: 15,
    fontWeight: '700',
  },
  phaseDescription: {
    color: '#63413C',
    fontSize: 12,
    lineHeight: 18,
  },
  phaseBadge: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 5,
    backgroundColor: '#F0ECEB',
  },
  phaseBadgeText: {
    color: '#5B3934',
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.7,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 14,
  },
  metricCard: {
    minHeight: 178,
    padding: 22,
    borderWidth: 1,
    borderColor: '#E3D9D7',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    justifyContent: 'space-between',
    boxShadow: '0 2px 4px rgba(40, 18, 15, 0.05)',
  },
  metricHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  metricTitle: {
    flex: 1,
    color: '#552A25',
    fontSize: 15,
    lineHeight: 21,
    fontWeight: '600',
  },
  metricIconContainer: {
    width: 39,
    height: 39,
    borderRadius: 9,
    backgroundColor: '#F5F0EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  metricIcon: {
    color: '#B80000',
    fontSize: 18,
    fontWeight: '800',
  },
  metricValue: {
    color: '#151110',
    fontSize: 29,
    fontWeight: '700',
    fontVariant: ['tabular-nums'],
  },
  metricDescription: {
    color: '#62433E',
    fontSize: 12,
    lineHeight: 17,
  },
  sectionHeading: {
    gap: 4,
  },
  sectionTitle: {
    color: '#181211',
    fontSize: 24,
    fontWeight: '800',
  },
  sectionSubtitle: {
    color: '#64433E',
    fontSize: 13,
  },
  quickActionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 14,
  },
  quickActionCard: {
    minHeight: 92,
    padding: 17,
    borderWidth: 1,
    borderColor: '#E3D9D7',
    borderRadius: 13,
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    boxShadow: '0 2px 4px rgba(40, 18, 15, 0.04)',
  },
  quickActionIconContainer: {
    width: 50,
    height: 50,
    flexShrink: 0,
    borderRadius: 10,
    backgroundColor: '#F2EEEE',
    alignItems: 'center',
    justifyContent: 'center',
  },
  quickActionIcon: {
    color: '#B60000',
    fontSize: 20,
    fontWeight: '800',
  },
  quickActionInformation: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  quickActionTitle: {
    color: '#241817',
    fontSize: 14,
    fontWeight: '700',
  },
  quickActionDescription: {
    color: '#654B47',
    fontSize: 12,
  },
  soonBadge: {
    flexShrink: 0,
    paddingHorizontal: 9,
    paddingVertical: 6,
    borderRadius: 5,
    backgroundColor: '#F0ECEB',
  },
  soonText: {
    color: '#604742',
    fontSize: 9,
    fontWeight: '600',
  },
  bottomGrid: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 24,
  },
  bottomGridNarrow: {
    flexDirection: 'column',
  },
  fullWidthCard: {
    width: '100%',
  },
  activityCard: {
    width: '58%',
    minHeight: 430,
    padding: 25,
    borderWidth: 1,
    borderColor: '#E3D9D7',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    boxShadow: '0 2px 4px rgba(40, 18, 15, 0.05)',
  },
  statusCard: {
    flex: 1,
    minHeight: 430,
    padding: 25,
    borderWidth: 1,
    borderColor: '#E3D9D7',
    borderRadius: 14,
    backgroundColor: '#FFFFFF',
    boxShadow: '0 2px 4px rgba(40, 18, 15, 0.05)',
  },
  cardHeading: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 15,
  },
  cardHeadingTitle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  cardTitle: {
    color: '#191312',
    fontSize: 20,
    fontWeight: '700',
  },
  eventBadge: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: '#F1EDEC',
  },
  eventBadgeText: {
    color: '#5C3D38',
    fontSize: 9,
  },
  historyText: {
    color: '#A58C87',
    fontSize: 11,
  },
  cardDivider: {
    height: 1,
    marginTop: 18,
    backgroundColor: '#E6DDDB',
  },
  emptyActivity: {
    flex: 1,
    minHeight: 280,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 14,
  },
  emptyIconContainer: {
    width: 67,
    height: 67,
    borderRadius: 34,
    backgroundColor: '#F4F0EF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyIcon: {
    color: '#A27973',
    fontSize: 34,
  },
  emptyTitle: {
    color: '#1D1615',
    fontSize: 17,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptyDescription: {
    maxWidth: 500,
    color: '#60433E',
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'center',
  },
  activityFooter: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#E6DDDB',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  activityFooterText: {
    color: '#74514C',
    fontSize: 11,
  },
  statusSubtitle: {
    paddingTop: 5,
    color: '#66443F',
    fontSize: 12,
  },
  statusRow: {
    minHeight: 66,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  statusDotGreen: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#12A650',
  },
  statusDotPending: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#D39A2C',
  },
  statusInformation: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  statusTitle: {
    color: '#201716',
    fontSize: 14,
    fontWeight: '700',
  },
  statusDescription: {
    color: '#654943',
    fontSize: 11,
    lineHeight: 16,
  },
  statusDivider: {
    height: 1,
    backgroundColor: '#E6DDDB',
  },
  successBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#C6EED4',
    borderRadius: 5,
    backgroundColor: '#EEFFF3',
  },
  successBadgeText: {
    color: '#08772E',
    fontSize: 9,
    fontWeight: '700',
  },
  pendingBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: '#F0DDB6',
    borderRadius: 5,
    backgroundColor: '#FFF8E8',
  },
  pendingBadgeText: {
    color: '#986714',
    fontSize: 9,
    fontWeight: '700',
  },
  updateIcon: {
    width: 17,
    color: '#6F302A',
    fontSize: 21,
    fontWeight: '700',
  },
  updateValue: {
    color: '#342321',
    fontSize: 11,
    fontWeight: '500',
  },
  businessCard: {
    marginTop: 16,
    padding: 17,
    borderWidth: 1,
    borderColor: '#E1D7D5',
    borderRadius: 10,
    backgroundColor: '#F7F3F2',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  businessIcon: {
    color: '#632A24',
    fontSize: 19,
    fontWeight: '700',
  },
  businessInformation: {
    flex: 1,
    gap: 4,
  },
  businessTitle: {
    color: '#271A18',
    fontSize: 14,
    fontWeight: '700',
  },
  businessDescription: {
    color: '#694B46',
    fontSize: 11,
    lineHeight: 17,
  },
});